### ISSUE TITLE
crashes reproducably on backspace in empty input control

### ISSUE THREAD

**Issue by vladtepesch** [OpenNingia/Launchy#28]
crashes reproducably on backspace in empty input control

a window opens that states that a dump is created somewhere but i could not find it.

![grafik](https://user-images.githubusercontent.com/1601159/105417923-9c990800-5c3c-11eb-9363-da9e79fa6053.png)

used latest version: launchy-v2.10.79 - however about page says 2.10.0 and installer even said 2.8.something

**Comment by OpenNingia** [comment]
Sorry about the versioning, it's a mess :)

About the crash, can you elaborate more on how you reproduce it? Just opening launchy and pressing `backspace` on the input while it's empty?

**Comment by vladtepesch** [comment]
> About the crash, can you elaborate more on how you reproduce it? Just opening launchy and pressing `backspace` on the input while it's empty?

yes. pressing alt+tab and pressing backspace to remove text. if the box is empty then it crashes

**Comment by OpenNingia** [comment]
Could you please try with this version? https://github.com/OpenNingia/Launchy/releases/tag/launchy-2.10.7xx

**Comment by vladtepesch** [comment]
the crash still occurs.
I cloned the repo and tried to debug the crash.
it seems that in the function `CommandHistory::search` `historyItem` is an empty list. so the `first()` call causes the crash

**Comment by vladtepesch** [comment]
without knowing the rest of the code and the implications that maybe come from this it seems that simple skipping empty entries at least prevents the crash.
  `if (historyItem.empty()) continue;`

**Comment by Grizaster** [comment]
Still crashes in V2.10.79 and in V2.10.715. Do I have to uninstall then install again? Shouldn't it be fixed on just update Launchy?
![grafik](https://user-images.githubusercontent.com/3832799/126514964-7d8afd13-eda1-4c1b-b038-6c8d52ff6f25.png)
