### ISSUE TITLE
Old plugins not working

### ISSUE THREAD

**Issue by achavazza** [OpenNingia/Launchy#6]
I've tried copying the old launchy plugins to this version. They aren't listed and dont work. 
I don't  know if is something broken or just not been supported

**Comment by OpenNingia** [comment]
themes are supported, but I fear old plugins are not. I did not try thou.

**Comment by snowkoan** [comment]
Too bad. I had the same issue. There are some real gems out there for the old Launch - weby, MathyResurrected, and more.

**Comment by snowkoan** [comment]
Did you change the plugin architecture? If you have some thoughts on why they don't work, I might take a stab at fixing it.

**Comment by OpenNingia** [comment]
The architecture is pretty much the same,but the dependencies are different.

Namely this launchy is build with Qt5 and VS 2015+

Il gio 5 ott 2017, 02:52 Alnoor <notifications@github.com> ha scritto:

**Comment by murcury** [comment]
Did anyone ever get the plugins working?

**Comment by Pimmetje** [comment]
I guess if u are able to recompile a old plugin it should work. I haven't tried this version but i think i will test it in the next week or so.
