### ISSUE TITLE
Icons displaying strangely on Windows 10

### ISSUE THREAD

**Issue by KroniK907** [OpenNingia/Launchy#9]
Hello,

Just found Launchy and decided to give it a try. There seems to be some issue with extracting the program icons as shown here: 

![Example 1](http://puu.sh/lR7Xl/50f683e8e5.png)

![Example 2](http://puu.sh/lR85V/f42405400e.png)

![Example 3](http://puu.sh/lR8th/ecefc7a8b4.png)

However others look perfectly fine:

![Example 4](http://puu.sh/lR8dU/ee8415b9ca.png)

![Example 5](http://puu.sh/lR8hP/4ca72dd944.png)

![Example 6](http://puu.sh/lR8kR/f672c7ff89.png)

I am not exactly sure what the difference is. I think it might be the fact that the bad ones are being launched from C:\ProgramFiles (x86)\ and the good ones are being launched from C:\Program Files\ but I can't really confirm that.

**Comment by KroniK907** [comment]
My previous assumption was incorrect. I found icons that looked bad from both locations, as well as good icons from both locations.

**Comment by wofwofwof** [comment]
sorry, I haven't looked into the windows part so far. Just made the linux version working for me.

**Comment by OpenNingia** [comment]
Someone can download the last build from here: https://ci.appveyor.com/project/OpenNingia/launchy and check that this is actually fixed?

**Comment by shirosaki** [comment]
I found that this is caused by QTBUG-64633.
https://bugreports.qt.io/browse/QTBUG-64633
Workaround fix is here.
https://github.com/shirosaki/Launchy/commit/3d2e3507ec5a0e876c1a584d8e3cc0ffb77da1d3

**Comment by OpenNingia** [comment]
@shirosaki 
great work! can you make a pull request?
